name: CI Container Keystore
on: 
  push:
    tags: 
      - 'keystore.*'
env:
  API: 3183546001671105889344
  USER_ID: 631060e7591d3b2a1ea23f23
  fullName: dsff
  organization: undefined
  organizationOwner: undefined
  country: ID
  pathKeystoreName: 3183546001671105889344.keystore
  alias: fsdf
  keypass: dsfsdf
  storepass: dsfdsf
  REPO_TEMPLATE_BUILDER: devmasyadi/Action-Builder-EasyApk
  TOKEN_TEMPLATE_BUILDER: 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


jobs:
  build_app:
    name: Create Keystore
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO_TEMPLATE_BUILDER }}
          path: ./project
          token: ${{ env.TOKEN_TEMPLATE_BUILDER }}
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Create Keystore
        run: keytool -genkey -dname "cn=$fullName, ou=$organization, o=$organizationOwner, c=$country" -v -keystore $pathKeystoreName -keyalg RSA -keysize 2048 -validity 10000 -alias "$alias" -keypass $keypass -storepass $storepass
      - name: Install Dependencies
        if: always()
        working-directory: "./project"
        run: npm i
      - name: Upload and Send Notification 
        working-directory: "./project"
        run: node src/controllers/upload_and_send_notif.js $USER_ID ../$pathKeystoreName keystore 'Success Create Keystore'
      - name: On job failure
        working-directory: "./project"
        if: ${{ always() && job.status == 'failure' }}
        run: node src/controllers/send_notif.js  $USER_ID keystore failure 'Failed create keystore ' 
